parameters:
    
    skip_frames: 1
    box_bottom_corner: [330,360]  # still needs to be set for cross_network= done
    box_top_corner: [690, 660]  # stil needs to be set for cross_network= done.

    y_t: 0 # yellow light traffic time

    resolutionInPixelsPerMeterX: 0.3
    resolutionInPixelsPerMeterY: 0.3

    scaling_factor: 1 # Used to scale the rewards, but for now set to 1.

    local_rewards: True
    waiting_penalty: True
    new_reward: False

# Either of the new_reward or waiting_penalty can be set True and not both.

    lightPositions: {"0": [[517.45,511.61], [511.5,502.5], [502.5,508.3], [508.4,517.4]]} # Need to know how to get the traffic light positions.

    libsumo: False # Need to know what happens if I set it to False, since inside the 
                   # sumogymadapter which initialises the ldm which in turn chooses between libsumo or traci.

    seed: 56 # somehow need to change seed for every episode so that new traffic routes are
             # generated each time we run an episode.
    
    test: False
    test_seed: [16753, 35821, 9675, 2193, 52120, 70142, 67371, 4470, 78146, 69491, 44398, 66521, 88094, 71935, 90747, 32224, 30813, 15315, 71678, 38054, 6603, 1548, 47881, 81064, 21234, 12045, 47394, 64234, 55742, 76628, 52041, 70833, 74947, 44494, 91087, 70947, 244, 98934, 79021, 13401, 41161, 91810, 26945, 95963, 74953, 50495, 44597, 9199, 49877, 11174, 6001, 86159, 77952, 34992, 22852, 59348, 51099, 70508, 80519, 1705, 519, 51981, 50890, 61316, 62326, 28126, 29789, 22896, 48838, 66610, 59605, 37138, 34603, 17813, 28854, 84745, 5619, 48512, 11048, 17969, 96893, 70589, 33158, 19271, 62747, 68573, 83723, 63231, 75189, 70400, 27676, 39515, 80968, 71245, 76315, 40902, 83779, 27613, 7180, 49900, 92638, 37183, 218, 72086, 94992, 30016, 5336, 29394, 342, 16485, 45074, 96782, 88523, 1327, 32975, 13650, 28287, 38212, 41881, 55057, 44535, 30397, 63857, 10723, 30494, 1081, 98205, 81131, 1978, 5346, 69451, 40907, 87321, 14233, 89945, 97496, 54902, 81897, 48036, 11772, 52784, 78513, 85243, 95980, 30087, 77631, 55783, 2856, 32152, 1974, 71394, 66344, 43379, 75610, 20339, 98997, 39679, 73777, 31461, 2744, 20752, 27285, 56695, 9578, 33377, 27407, 25265, 53655, 48360, 51302, 69051, 29235, 67874, 16822, 85823, 23468, 35957, 28553, 91540, 22329, 26897, 67403, 90368, 62976, 94703, 32116, 44268, 61924, 37747, 10636, 73353, 11102, 29185, 56504, 85752, 61712, 95657, 46835, 97009, 31107, 42857, 56536, 3277, 20655, 73345, 12456, 14622, 23565, 20779, 49317, 75471, 31301, 55758, 37013, 8590, 33527, 39374, 61430, 51931, 22351, 23397, 16401, 667, 91750, 97724, 49020, 34680, 20167, 88733, 1799, 45066, 75749, 8326, 6911, 7618, 76986, 13284, 74882, 48870, 22983, 68410, 86232, 81378, 8677, 14208, 57203, 94161, 81021, 23370, 53455, 20199, 29971, 40482, 68265, 72678, 10701, 88885, 4846, 79396, 34744, 35947, 13742, 41976, 59096, 58847, 29818, 49595, 8265, 50044, 36756, 26517, 60680, 31456, 45649, 77814, 62159, 42496, 65301, 29853, 36936, 83433, 16972, 916, 69682, 98906, 31583, 46397, 22448, 3488, 88017, 56644, 20103, 81713, 984, 31806, 24993, 26733, 67021, 13796, 96423, 78765, 11376, 85746, 89046, 22913, 95062, 49069, 53543, 78111, 95754, 91610, 81695, 28978, 51035, 53125, 97342, 72687, 75144, 71121, 76862, 91865, 80265, 6307, 19556, 90269, 42388, 74668, 89278, 63987, 66342, 58574, 37137, 67865, 44478, 28281, 98607, 92907, 32403, 14974, 3640, 23451, 50645, 54643, 79868, 62107, 25625, 89047, 45727, 49452, 81615, 43786, 63757, 15561, 90334, 31486, 33164, 75990, 55012, 19740, 43814, 31560, 54996, 30266, 29368, 95038, 51713, 86276, 11714, 51849, 11223, 90542, 90607, 39430, 6356, 12149, 84815, 12679, 91840, 27947, 92953, 31997, 38220, 19092, 88544, 86084, 36983, 26614, 15745, 15642, 58805, 76691, 73491, 44475, 79093, 8051, 47677, 42466, 13491, 62199, 19421, 37070, 93558, 70050, 4675, 70159, 69151, 67837, 47805, 77032, 12808, 11367, 51134, 28081, 80190, 26564, 52910, 29136, 3017, 80148, 99278, 70427, 44725, 6351, 75343, 94092, 30776, 2472, 87094, 90779, 33627, 82158, 55910, 65214, 70269, 59674, 99730, 30057, 1590, 30299, 10368, 14833, 80531, 3168, 20979, 14588, 10623, 35917, 60462, 58079, 23840, 14850, 50896, 9883, 44028, 40221, 43558, 2369, 5464, 28672, 70783, 51823, 75145, 11642, 39496, 14443, 3440, 27041, 17660, 19670, 44239, 80578, 86289, 83659, 87853, 66826, 26909, 66551, 27269, 69921, 612, 20303, 87956, 97294, 63537, 1263, 19801, 51994, 53251, 14953, 22425, 82085, 49688, 37020, 38108, 17585, 45149, 43273, 88443, 69016, 64]

    generate_conf: True # it is used inside the sumohelper.py It is used to generate the sumoconfig file from the nodes, edges etc.

    tlphasesfile: 'cross.net.xml'
    route_starts: []
    route_ends: []
    route_max_segments: 1
    route_min_segments: 1
    route_segments: ['51o 1i 2o 52i', '54o 4i 3o 53i', '52o 2i 1o 51i', '53o 3i 4o 54i']

# For now only add array of segments that will define the route of your vehicle.
# These are used inside sumphlper.py's generate_randomized_route() function in order to 
# generate routes.

    car_pr: 0.2
    car_tm: 500

# These are used to generate vehicle for each possible route in the scenario and writes
# them to a file and returns the location of the sumocfg file.

    scene: 'cross_network' 

# This is used to define the directory where we save the file for route and configuration.
# Its inside the scenario directory.

    gui: False
    type: 'byCorners'
    speed_dev: 0.0
    verbose: 0
